Implemented hex_get_bytes function
democritus-project/d8s-math pull request #6
Opened 2021-05-12 05:18 UTC by zh-beep

Hi @fhightower - thank you for the opportunity to contribute, I have added and tested this function. It returns a string represented in hex.

2021-05-21 11:24 UTC, fhightower requested changes
Thanks for working on this @zh-beep ! I do have a few questions, though.

I was testing your function with the hex value `0x12345678` and got the following results:

```python
hex_get_bytes(0x12345678, 1)  # '0x123456'
hex_get_bytes(0x12345678, 2)  # '0x1234'
hex_get_bytes(0x12345678, 3)  # '0x12'
hex_get_bytes(0x12345678, 4)  # '0'
```

Unfortunately, those results are not correct. Below is a table showing the value returned by the function in this PR and the correct values:

| Function Call | Actual Result  | Correct Result |
--- | --- | ---
`hex_get_bytes(0x12345678, 1)` | `'0x123456'` | `'0x12'`
`hex_get_bytes(0x12345678, 2)` | `'0x1234'` | `'0x1234'`
`hex_get_bytes(0x12345678, 3)` | `'0x12'` | `'0x123456'`
`hex_get_bytes(0x12345678, 4)` | `'0'` | `'0x12345678'`

Does that make sense?

As described in the "Byte" section [here](http://www.edu4java.com/en/concepts/hexadecimal-binary-number-byte-bit-word.html), each byte is represented in hexadecimal as two hexadecimal characters. So, `0x12345678` in hexadecimal represents four bytes (`12` represents one byte, `34` another byte, `56` another, and `78` another). So, if we want to get one byte of `0x12345678`, we expect to get `'0x12'`. Two bytes would give us `'0x1234'` and three would give us `'0x123456'`.

The actual output appears to be the reverse of what we want, so there should be a relatively each change to make it work properly.

2021-05-21 11:24 UTC, fhightower commented on d8s_math/maths.py
> +def hex_get_bytes(hex_number,number_of_bytes):
Minor style improvement:

```suggestion
def hex_get_bytes(hex_number, number_of_bytes):
```

2021-05-21 11:24 UTC, fhightower commented on d8s_math/maths.py
> +
I recommend removing the line between the `if` and `else`:

```suggestion
```

2021-05-22 06:46 UTC, zh-beep commented
@fhightower - I updated the function - thank you for your help and for pointing out my mistake. I also updated the README to include the hex_get_bytes function.

I used [this package](https://github.com/gruns/icecream) to automate printing/debugging - thought it was pretty nifty: 

![image](https://user-images.githubusercontent.com/10417016/119217059-48dce500-ba9d-11eb-84df-833140a64227.png)

2021-05-25 10:22 UTC, fhightower commented
Nice, looks good! I'll merge this in 🎉 .

2021-05-25 10:22 UTC, merged